// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:vitaminc/core/models/sync_queue_item.dart';
import 'package:vitaminc/core/models/vocab_local.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(SyncQueueItemAdapter());
    registerAdapter(VocabLocalAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(SyncQueueItemAdapter());
    registerAdapter(VocabLocalAdapter());
  }
}
